### ISSUE TITLE
Consolidate DI pattern on the ApiModule

### ISSUE THREAD

**Issue by hoangnguyen92dn** [ryan-conway/survey-exam#15]
- [x] It makes sense to have the ApiModule for the network stuff, besides that with the DI pattern, you are creating the instance of Moshi, Interceptor, and OkHttpClient directly inside `provideRetrofit` , it's violating the pattern. I'd suggest separating the instance's creation and it is also easier to show dependencies between objects.

https://github.com/ryan-conway/survey-exam/blob/3ae3ac7e7b31a83f05f04c084f8cac601b8a12ba/app/src/main/java/com/example/nimblesurveys/di/ApiModule.kt#L19-L35

**Comment by ryan-conway** [comment]
@hoangnguyen92dn I can see your point here. My reasoning here was we only pass a retrofit instance to the other dependencies, but I can see how it violates the pattern now, will update this

**Comment by ryan-conway** [comment]
Separated creation of retrofit dependencies in PR #21
