### ISSUE TITLE
Secret the API credentials with the build process

### ISSUE THREAD

**Issue by hoangnguyen92dn** [ryan-conway/survey-exam#3]
- [x] Secret the API credentials with the build process

With your current implementation, the API credentials could be leaked by reverse engineering. Furthermore, whenever the credentials change, we have to modify the `AuthModule`; it doesn't make sense because the class is only updated with the logic changes in my opinion. I think we could configure the credentials secret with the build process, how do you think?

https://github.com/ryan-conway/survey-exam/blob/01c21ba788434cccf0867853532dd478fd548557/app/src/main/java/com/example/nimblesurveys/di/AuthModule.kt#L23-L25

**Comment by ryan-conway** [comment]
@hoangnguyen92dn api credentials have been moved to `auth.gradle` file. 
Please let me know where I can send the file to you if needed since this shouldn't normally be stored in the project's repo 😄

**Comment by hoangnguyen92dn** [comment]
@ryan-conway I think you don't need to send me the file; I will create it on my local for usage. You just need to show me the file location and how to define the value in `auth.gradle`.
Just in case you didn't know, another approach is using `.properties` file to define the credentials, then we will read the value from `.properties` file.

**Comment by ryan-conway** [comment]
@hoangnguyen92dn `auth.gradle` is placed in the project root folder, with the contents like this:
```
ext {
    SURVEY_API_PROD = "\"{{PROD_URL}}\""
    SURVEY_API_STAGING = "\"{{STAGING_URL}}\""

    SURVEY_KEY = "\"{{API_KEY}}\""
    SURVEY_SECRET = "\"{{API_SECRET}}\""
}
```

I was unaware of the `.properties` method, I'll look into that 😄
