### ISSUE TITLE
Missing Splash screen and application requires login everytime on launched

### ISSUE THREAD

**Issue by hoangnguyen92dn** [ryan-conway/survey-exam#6]
- [x] According to the design on Figma, there is a Splash screen to show before navigating the user to the Home or Login screen. If you didn't have enough time to handle it before submission, please consider adding it during the code review process.

<img src ="https://user-images.githubusercontent.com/6950766/143258560-8301e9c5-333b-433b-814c-af1bf2439866.png" width=450>

- [x] One more issue related to authentication is the application keep showing the Login screen although logged in on the previous launch. Would it be possible to validate the authentication status before displaying the Login screen?

**Comment by ryan-conway** [comment]
Noted on these, will work on them now

**Comment by hoangnguyen92dn** [comment]
@ryan-conway I will continue to review the rest of your submission tomorrow, you still have time to resolve the issue in the next following days 😄  I am off now btw. Good night 🛌  🌙

**Comment by ryan-conway** [comment]
@hoangnguyen92dn I have added the splash screen and additional login logic on the develop branch 😄
